//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.08 at 06:07:24 PM CST 
//


package com.thenetcircle.comsumerdispatcher.config.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{tnc}request-pre"/>
 *         &lt;element ref="{tnc}request-count"/>
 *         &lt;element ref="{tnc}request-timeout"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestPre",
    "requestCount",
    "requestTimeout"
})
@XmlRootElement(name = "conf")
public class Conf {

    @XmlElement(name = "request-pre", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String requestPre;
    @XmlElement(name = "request-count", required = true)
    protected BigInteger requestCount;
    @XmlElement(name = "request-timeout", required = true)
    protected BigInteger requestTimeout;

    /**
     * Gets the value of the requestPre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestPre() {
        return requestPre;
    }

    /**
     * Sets the value of the requestPre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestPre(String value) {
        this.requestPre = value;
    }

    /**
     * Gets the value of the requestCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestCount() {
        return requestCount;
    }

    /**
     * Sets the value of the requestCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestCount(BigInteger value) {
        this.requestCount = value;
    }

    /**
     * Gets the value of the requestTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestTimeout() {
        return requestTimeout;
    }

    /**
     * Sets the value of the requestTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestTimeout(BigInteger value) {
        this.requestTimeout = value;
    }

}
