//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.08 at 06:07:24 PM CST 
//


package com.thenetcircle.comsumerdispatcher.config.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="httpHost" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="httpPort" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="rHost" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rPort" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "monitor")
public class Monitor {

    @XmlAttribute(name = "httpHost", required = true)
    protected String httpHost;
    @XmlAttribute(name = "httpPort", required = true)
    protected BigInteger httpPort;
    @XmlAttribute(name = "rHost", required = true)
    protected String rHost;
    @XmlAttribute(name = "rPort", required = true)
    protected BigInteger rPort;

    /**
     * Gets the value of the httpHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttpHost() {
        return httpHost;
    }

    /**
     * Sets the value of the httpHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttpHost(String value) {
        this.httpHost = value;
    }

    /**
     * Gets the value of the httpPort property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHttpPort() {
        return httpPort;
    }

    /**
     * Sets the value of the httpPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHttpPort(BigInteger value) {
        this.httpPort = value;
    }

    /**
     * Gets the value of the rHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRHost() {
        return rHost;
    }

    /**
     * Sets the value of the rHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRHost(String value) {
        this.rHost = value;
    }

    /**
     * Gets the value of the rPort property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRPort() {
        return rPort;
    }

    /**
     * Sets the value of the rPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRPort(BigInteger value) {
        this.rPort = value;
    }

}
