//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.08 at 06:07:24 PM CST 
//


package com.thenetcircle.comsumerdispatcher.config.xml;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.thenetcircle.comsumerdispatcher.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestPre_QNAME = new QName("tnc", "request-pre");
    private final static QName _RequestCount_QNAME = new QName("tnc", "request-count");
    private final static QName _RequestTimeout_QNAME = new QName("tnc", "request-timeout");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thenetcircle.comsumerdispatcher.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Monitor }
     * 
     */
    public Monitor createMonitor() {
        return new Monitor();
    }

    /**
     * Create an instance of {@link Conf }
     * 
     */
    public Conf createConf() {
        return new Conf();
    }

    /**
     * Create an instance of {@link Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link Servers }
     * 
     */
    public Servers createServers() {
        return new Servers();
    }

    /**
     * Create an instance of {@link Queueserver }
     * 
     */
    public Queueserver createQueueserver() {
        return new Queueserver();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tnc", name = "request-pre")
    public JAXBElement<String> createRequestPre(String value) {
        return new JAXBElement<String>(_RequestPre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tnc", name = "request-count")
    public JAXBElement<BigInteger> createRequestCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_RequestCount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tnc", name = "request-timeout")
    public JAXBElement<BigInteger> createRequestTimeout(BigInteger value) {
        return new JAXBElement<BigInteger>(_RequestTimeout_QNAME, BigInteger.class, null, value);
    }

}
