//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.08 at 06:07:24 PM CST 
//


package com.thenetcircle.comsumerdispatcher.config.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="host" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="port" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="redisHost" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="redisPort" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="retryIntervalSeconds" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="userName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vhost" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "queueserver")
public class Queueserver {

    @XmlAttribute(name = "host", required = true)
    protected String host;
    @XmlAttribute(name = "logFileName")
    protected String logFileName;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "password", required = true)
    protected String password;
    @XmlAttribute(name = "port", required = true)
    protected BigInteger port;
    @XmlAttribute(name = "redisHost")
    protected String redisHost;
    @XmlAttribute(name = "redisPort")
    protected BigInteger redisPort;
    @XmlAttribute(name = "retryIntervalSeconds")
    protected BigInteger retryIntervalSeconds;
    @XmlAttribute(name = "userName", required = true)
    protected String userName;
    @XmlAttribute(name = "vhost", required = true)
    protected String vhost;

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the logFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFileName() {
        return logFileName;
    }

    /**
     * Sets the value of the logFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFileName(String value) {
        this.logFileName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPort(BigInteger value) {
        this.port = value;
    }

    /**
     * Gets the value of the redisHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedisHost() {
        return redisHost;
    }

    /**
     * Sets the value of the redisHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedisHost(String value) {
        this.redisHost = value;
    }

    /**
     * Gets the value of the redisPort property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRedisPort() {
        return redisPort;
    }

    /**
     * Sets the value of the redisPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRedisPort(BigInteger value) {
        this.redisPort = value;
    }

    /**
     * Gets the value of the retryIntervalSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetryIntervalSeconds() {
        return retryIntervalSeconds;
    }

    /**
     * Sets the value of the retryIntervalSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetryIntervalSeconds(BigInteger value) {
        this.retryIntervalSeconds = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the vhost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVhost() {
        return vhost;
    }

    /**
     * Sets the value of the vhost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVhost(String value) {
        this.vhost = value;
    }

}
